services:
  pellito-hub:
    build:
      context: .
      dockerfile: Dockerfile
    image: pellito-hub:latest
    container_name: pellito-hub
    hostname: pellito-hub
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - pellito-data:/app/data
    networks:
      - nginx-proxy

volumes:
  pellito-data:

networks:
  nginx-proxy:
    external: true
